### ISSUE TITLE
Why execute command throwing Command #1 returned exit status 1 exception?

### ISSUE THREAD

**Issue by bilalsha** [int128/gradle-ssh-plugin#170]
I am deploying the war file to tomcat. It copies and deploy the war successfully but the gradle script is failing somehow throwing this exception
```
Caused by: org.hidetake.groovy.ssh.session.BadExitStatusException: Command #1 returned exit status 1
	at org.hidetake.groovy.ssh.operation.DefaultOperations.execute(DefaultOperations.groovy:112)
	at org.hidetake.groovy.ssh.operation.Operations$execute$0.call(Unknown Source)
	at org.hidetake.groovy.ssh.extension.Command$Trait$Helper.execute(Command.groovy:35)
	at org.hidetake.groovy.ssh.extension.Command$Trait$Helper$execute$0.call(Unknown Source)
	at org.hidetake.groovy.ssh.session.SessionHandler.execute(SessionHandler.groovy)
	at deploy_7q7vu63modu0zqiano2rqfd8x$_run_closure3_closure5_closure6.doCall(/Projects/upwork/tiyago/AnalyticsService/scripts/deploy.gradle:22)
```

At line 22 it is execute command which is

```execute('sudo service tomcat restart')```

here is my script

```
remotes {
    tomcatDeploy {
        host = project.property('tomcat.host')
        user = project.property('tomcat.host.user')
        password = project.property('tomcat.host.password')
    }
}

ext.webappsDir = project.property('tomcat.host.webapps.dir')
war.archiveName = project.property('war.name')

task deploy(dependsOn: war) << {
    ssh.run {
        session(remotes.tomcatDeploy) {
            put(war.archivePath.path, webappsDir)
            execute('sudo service tomcat restart'){ result ->
                println result
            }
        }
    }
}
```

What am I doing wrong here?

Here is the log using ```grade -d``` command 

```
00:24:18.558 [INFO] [org.hidetake.groovy.ssh.operation.FileTransferLogger] Starting transfer 57,298,387 bytes.
00:24:22.637 [INFO] [org.hidetake.groovy.ssh.operation.FileTransferLogger] Transferred 74% in 4.077 secs.
00:24:23.033 [INFO] [org.hidetake.groovy.ssh.operation.FileTransferLogger] Finished transfer 57,298,387 bytes (12,796 kB/s). Took 4.479 secs.
00:24:23.040 [INFO] [org.hidetake.groovy.ssh.operation.SftpOperations] Sent the local file (/Projects/upwork/tiyago/AnalyticsService/build/libs/AnalyticsService-0.1.war) into the remote file (/opt/tomcat/webapps)
00:24:23.042 [DEBUG] [org.hidetake.groovy.ssh.operation.DefaultOperations] SFTP #0 closed
00:24:23.622 [DEBUG] [org.hidetake.groovy.ssh.operation.DefaultOperations] Executing the command (sudo service tomcat restart) with org.hidetake.groovy.ssh.core.settings.OperationSettings(false, false, false, stdout, null, null, UTF-8, null, [])
00:24:23.654 [INFO] [org.hidetake.groovy.ssh.operation.DefaultOperations] Command #1 started (sudo service tomcat restart)
00:24:24.709 [DEBUG] [org.hidetake.groovy.ssh.operation.LineOutputStream] Flushing the buffer
00:24:24.934 [ERROR] [system.err] tomcatDeploy|sudo: no tty present and no askpass program specified
00:24:24.937 [DEBUG] [org.hidetake.groovy.ssh.operation.LineOutputStream] Flushed the buffer
00:24:24.938 [DEBUG] [org.hidetake.groovy.ssh.operation.LineOutputStream] Closing the stream
00:24:24.945 [DEBUG] [org.hidetake.groovy.ssh.operation.LineOutputStream] Closed the stream
00:24:24.952 [DEBUG] [org.hidetake.groovy.ssh.operation.LineOutputStream] Closing the stream
00:24:24.953 [DEBUG] [org.hidetake.groovy.ssh.operation.LineOutputStream] Closed the stream
00:24:24.959 [INFO] [org.hidetake.groovy.ssh.operation.DefaultOperations] Command #1 returned exit status 1
00:24:24.982 [DEBUG] [org.hidetake.groovy.ssh.connection.ConnectionManager] Waiting for pending operations
00:24:25.016 [DEBUG] [org.hidetake.groovy.ssh.connection.ConnectionManager] Finished all operations including background commands
00:24:25.019 [DEBUG] [org.hidetake.groovy.ssh.connection.JSchLogger] JSch: Disconnecting from localhost port 22
00:24:25.026 [DEBUG] [org.hidetake.groovy.ssh.connection.JSchLogger] JSch: Caught an exception, leaving main loop due to Socket closed
00:24:25.040 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':deploy'
00:24:25.040 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :deploy FAILED
00:24:25.041 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :deploy (Thread[main,5,main]) completed. Took 20.722 secs.
00:24:25.042 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 51.487 secs, idle: 0.011 secs
00:24:25.130 [ERROR] [org.gradle.BuildExceptionReporter] 
00:24:25.142 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
00:24:25.144 [ERROR] [org.gradle.BuildExceptionReporter] 
00:24:25.147 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
00:24:25.148 [ERROR] [org.gradle.BuildExceptionReporter] Script '/Projects/upwork/tiyago/AnalyticsService/scripts/deploy.gradle' line: 22
00:24:25.155 [ERROR] [org.gradle.BuildExceptionReporter] 
00:24:25.155 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
00:24:25.155 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':deploy'.
00:24:25.156 [ERROR] [org.gradle.BuildExceptionReporter] > Command #1 returned exit status 1
00:24:25.156 [ERROR] [org.gradle.BuildExceptionReporter] 
00:24:25.156 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
00:24:25.157 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
00:24:25.158 [LIFECYCLE] [org.gradle.BuildResultLogger] 
00:24:25.158 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
00:24:25.159 [LIFECYCLE] [org.gradle.BuildResultLogger] 
00:24:25.159 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 1 mins 10.827 secs
00:24:25.164 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopping 0 compiler daemon(s).
00:24:25.164 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonManager] Stopped 0 compiler daemon(s).
``` 

Thanks for the help in advance.

**Comment by int128** [comment]
`sudo` command may need to be run with PTY by default for security reason. Please replace the line with following:
```groovy
execute('sudo service tomcat restart', pty: true)
```
Thanks.

**Comment by krmao** [comment]
I still get this error

```
task deploy {
    doLast {
        ssh.runInOrder {
            session(remotes.serverHousekeeper) {
//                put from: "$buildDir/libs/background.war", into: '/usr/software/tomcat/apache-tomcat-8.5.24/webapps/'

                execute("sudo rm -rf /usr/software/tomcat/apache-tomcat-8.5.24/webapps/background", pty: true)// { result -> println result }
                execute("sudo sh /usr/software/tomcat/apache-tomcat-8.5.24/bin/shutdown.sh", pty: true) //{ result -> println result }
                execute("sudo sh /usr/software/tomcat/apache-tomcat-8.5.24/bin/startup.sh", pty: true) //{ println result }
            }
        }
    }
}
```


```
> Configure project :app-background
copyConfigFile startcopyConfigFile end
serverHousekeeper#15|Neither the JAVA_HOME nor the JRE_HOME environment variable is defined
serverHousekeeper#15|At least one of these environment variable is needed to run this program

> Task :app-background:deploy FAILED
Failed command serverHousekeeper#15 with status 1: sudo sh /usr/software/tomcat/apache-tomcat-8.5.24/bin/shutdown.sh


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/maokangren/workspace/house-keeper/servers/service-hk-background/arsenal/apps/app-background/build.gradle' line: 60

* What went wrong:
Execution failed for task ':app-background:deploy'.
> Command returned exit status 1: sudo sh /usr/software/tomcat/apache-tomcat-8.5.24/bin/shutdown.sh

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app-background:deploy'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.hidetake.groovy.ssh.session.BadExitStatusException: Command returned exit status 1: sudo sh /usr/software/tomcat/apache-tomcat-8.5.24/bin/shutdown.sh
        at org.hidetake.groovy.ssh.session.execution.Command$Helper.execute(Command.groovy:52)
        at org.hidetake.groovy.ssh.session.execution.Command$Trait$Helper.execute(Command.groovy:30)
        at org.hidetake.groovy.ssh.session.execution.Command$Trait$Helper$execute$0.call(Unknown Source)
        at org.hidetake.groovy.ssh.session.SessionHandler.execute(SessionHandler.groovy)
        at build_alqxv62xnw967ga2x7bp11z7e$_run_closure8$_closure14$_closure15$_closure16.doCall(/Users/maokangren/workspace/house-keeper/servers/service-hk-background/arsenal/apps/app-background/build.gradle:60)
        at build_alqxv62xnw967ga2x7bp11z7e$_run_closure8$_closure14$_closure15$_closure16.doCall(/Users/maokangren/workspace/house-keeper/servers/service-hk-background/arsenal/apps/app-background/build.gradle)
        at org.hidetake.groovy.ssh.util.Utility.callWithDelegate(Utility.groovy:17)
        at org.hidetake.groovy.ssh.session.SessionTask.wetRun(SessionTask.groovy:64)
        at org.hidetake.groovy.ssh.session.SessionTask.call(SessionTask.groovy:48)
        at java_util_concurrent_Callable$call.call(Unknown Source)
        at org.hidetake.groovy.ssh.core.Service.runInOrder(Service.groovy:97)
        at org.hidetake.groovy.ssh.core.Service$runInOrder.call(Unknown Source)
        at org.hidetake.groovy.ssh.core.Service$runInOrder.call(Unknown Source)
        at build_alqxv62xnw967ga2x7bp11z7e$_run_closure8$_closure14.doCall(/Users/maokangren/workspace/house-keeper/servers/service-hk-background/arsenal/apps/app-background/build.gradle:55)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:722)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:695)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

```
