### ISSUE TITLE
SFTP: rmrf support

### ISSUE THREAD

**Issue by mvysny** [int128/gradle-ssh-plugin#185]
Currently I am deleting dirs via SFTP as follows:

    boolean exists(String dir, Object sftp) {
        try {
            sftp.channel.stat(dir)
            return true
        } catch (Exception ex) {
            if (ex.class.getName() == 'com.jcraft.jsch.SftpException' && ex.id == 2) {
                // file not found
                return false
            }
            throw ex
        }
    }

    /**
     * Deletes given directory recursively via SFTP.
     * @param dir the directory to delete, absolute. May not exist.
     * @param d gradle-ssh-plugin sftp delegate.
     */
    ext.rmrf = {String dir, Object sftp ->
        // check whether the directory exists.
        if (!exists(dir, sftp)) {
            // file not found, nothing to do
            return
        }
        sftp.ls(dir).each {
            if (!(it.filename in ['.', '..'])) {
                // it is of type JSch ChannelSftp.LsEntry
                // sftp.channel is of type JSch ChannelSftp
                String fullPath = "$dir/${it.filename}"
                if (it.attrs.reg) {
                    // regular file
                    sftp.channel.rm fullPath
                } else if (it.attrs.dir) {
                    // a directory
                    rmrf(fullPath, sftp)
                } else {
                    // unknown type, leave it be
                }
            }
        }
        sftp.channel.rmdir dir
    }

Then, in session, I simply call

    sftp {
        project.rmrf(dir, delegate)
        mkdir dir
    }

It would be nice to add rmrf and exists to your great toolbox of sftp functions ;) Thanks!

**Comment by int128** [comment]
It will be added as `remove()` method in 1.3.0. Thanks for the idea.

**Comment by mvysny** [comment]
Thank you very much for including this. I confirm that the remove() works great.

**Comment by mvysny** [comment]
I found out that the remove() method fails if the directory does not exist:

> Caused by: org.hidetake.groovy.ssh.operation.SftpException: Failed SFTP STAT: docserver:/docs/lsps/doc_root/Stage3_2: (SSH_FX_NO_SUCH_FILE: A reference was made to a file which does not exist): No such file
	at org.hidetake.groovy.ssh.operation.SftpOperations.stat(SftpOperations.groovy:187)
	at org.hidetake.groovy.ssh.extension.SftpRemove$Trait$Helper$_remove_closure1$_closure2.doCall(SftpRemove.groovy:18)
	at org.hidetake.groovy.ssh.extension.SftpRemove$Trait$Helper$_remove_closure1.doCall(SftpRemove.groovy:17)
	at org.hidetake.groovy.ssh.extension.SftpRemove$Trait$Helper$_remove_closure1.doCall(SftpRemove.groovy)
Caused by: 2: No such file
	at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2846)
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2198)
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2215)
	at com.jcraft.jsch.ChannelSftp.stat(ChannelSftp.java:2172)
	at com.jcraft.jsch.ChannelSftp$stat.call(Unknown Source)
	at org.hidetake.groovy.ssh.operation.SftpOperations.stat(SftpOperations.groovy:182)
	... 91 more


You can employ the `exists()` function I wrote earlier to check whether the file exists, at `SftpRemove.groovy:18`. Can I please reopen this bug, or should I file a new bug?
