### ISSUE TITLE
Increase channel timeout option for slow hosts

### ISSUE THREAD

**Issue by johnjaylward** [int128/gradle-ssh-plugin#250]
I have a host that is sometimes slow to connect to (between 30 and 60 seconds). Adding a configuration option to increase the default channel timeout would be helpful so my scripts don't fail prematurely.

http://stackoverflow.com/questions/28038747/what-is-the-default-timeout-for-session-and-channel-in-jsch-library-in-java

The newest javadoc seems to indicate that 50 seconds is the new default upper limit when no specific timeout is used.
https://epaul.github.io/jsch-documentation/simple.javadoc/com/jcraft/jsch/Channel.html#connect(int)

**Comment by stephencsmall** [comment]
+1 for this feature.  I have a number of deployment targets that intermittently take upwards of 30s to open a channel, and it would be great to be able to extend the default channel timeout.

@int128 if you need someone to implement this feature, I think this would be within my ability and my company would see immediate benefit from it, so please let me know if I can help.

**Comment by int128** [comment]
Hi. This feature is already implemented and ready to release. I will release 2.5.0 today or tomorrow.

**Comment by int128** [comment]
This feature has been released in 2.5.0. Please try `timeoutSec` setting.

**Comment by stephencsmall** [comment]
@int128 I upgraded my builds to 2.5.0 and implemented the `timeoutSec` setting today. Unfortunately it does not seem cover the creation of a channel.  In my environment, deployment targets are successfully opening a connection, but failing to return a channel quickly enough, which leads to the following exception:

```
Caused by: com.jcraft.jsch.JSchException: channel is not opened.
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:765)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at com.jcraft.jsch.Channel$connect.call(Unknown Source)
	at org.hidetake.groovy.ssh.operation.DefaultOperations.sftp(DefaultOperations.groovy:73)
	at org.hidetake.groovy.ssh.operation.Operations$sftp.call(Unknown Source)
	at org.hidetake.groovy.ssh.session.transfer.put.Sftp.put(Sftp.groovy:23)
	at org.hidetake.groovy.ssh.session.transfer.put.Sftp$put.call(Unknown Source)
	at org.hidetake.groovy.ssh.session.transfer.FilePut$Trait$Helper.putInternal(FilePut.groovy:126)
	at org.hidetake.groovy.ssh.session.transfer.FilePut$Trait$Helper.putInternal(FilePut.groovy:79)
	at org.hidetake.groovy.ssh.session.transfer.FilePut$Trait$Helper.putInternal(FilePut.groovy:89)
	at org.hidetake.groovy.ssh.session.transfer.FilePut$Trait$Helper.put(FilePut.groovy:40)
	at org.hidetake.groovy.ssh.session.transfer.FilePut$Trait$Helper$put.call(Unknown Source)
	at org.hidetake.groovy.ssh.session.SessionHandler.put(SessionHandler.groovy)
	at com.rez1.build.core.deploy.Rez1DeployPlugin$_apply_closure1$_closure2$_closure12$_closure36$_closure37$_closure38.doCall(Rez1DeployPlugin.groovy:168)
	at com.rez1.build.core.deploy.Rez1DeployPlugin$_apply_closure1$_closure2$_closure12$_closure36$_closure37$_closure38.doCall(Rez1DeployPlugin.groovy)
	at org.hidetake.groovy.ssh.util.Utility.callWithDelegate(Utility.groovy:17)
	at org.hidetake.groovy.ssh.session.Executor$_wetRun_closure2.doCall(Executor.groovy:71)
	at org.hidetake.groovy.ssh.session.Executor.wetRun(Executor.groovy:66)
	at org.hidetake.groovy.ssh.session.Executor.execute(Executor.groovy:50)
	at org.hidetake.groovy.ssh.session.Executor$execute.call(Unknown Source)
	at org.hidetake.groovy.ssh.core.Service.run(Service.groovy:78)
	at org.hidetake.groovy.ssh.core.Service$run$1.call(Unknown Source)
	at com.rez1.build.core.deploy.Rez1DeployPlugin$_apply_closure1$_closure2$_closure12$_closure36.doCall(Rez1DeployPlugin.groovy:166)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
```

I propose that when calling the `channel.connect()` method, instead call `connect(int connectTimeout) ` using the same timeoutSec property that was implemented for connection and session.  This would allow more time to receive the channel open response from the server, and prevent the above exception.  For example, see Command.groovy, line 66:

```
 @Override
    int startSync() {
        channel.connect()  // Can also be called with a timeout value (connect(int connectTimeout))
        log.info("Started command $connection.remote.name#$channel.id: $commandLine")
        try {
            interactions.start()
            interactions.waitForEndOfStream()
            log.debug("Waiting for command $connection.remote.name#$channel.id: $commandLine")
            while (!channel.closed) {
                sleep(100)
            }
            int exitStatus = channel.exitStatus
            if (exitStatus == 0) {
                log.info("Success command $connection.remote.name#$channel.id: $commandLine")
            } else {
                log.error("Failed command $connection.remote.name#$channel.id with status $exitStatus: $commandLine")
            }
            exitStatus
        } finally {
            channel.disconnect()
        }
    }
```

I'd be happy to fork, implement the change, and file a new PR specifically for channel timeouts if you would prefer.  I'm glad to help in any way I can.

**Comment by int128** [comment]
Oops. I mistake channel timeout for connection timeout. Currently `timeoutSec` property is not available in operation layer (i.e. `Command`, `Shell` and `DefaultOperations`) and some design change seems needed. I will add implementation for channel timeout. Thank you.

**Comment by int128** [comment]
@stephencsmall Released 2.5.1. Would you try again?

**Comment by stephencsmall** [comment]
@int128 I applied the new version to my deployments yesterday and I've seen good results so far.  The timeout is working for channels now, and remotes that I was previously seeing failures on are now stabilized.  Thank you very much for implementing this change so quickly, it has been a huge improvement for my organization's Gradle deployments.

**Comment by johnjaylward** [comment]
Same, I performed a deployment yesterday as well and it went smoothly. No more timeout errors in the logs.
