### ISSUE TITLE
'get' no longer creates sub-directories automatically

### ISSUE THREAD

**Issue by skazzyy** [int128/gradle-ssh-plugin#278]
Between 2.3.0 and 2.4.0, you can no longer get a file or directory into a local directory that doesn't exist.
### Environment info

gradle-ssh-plugin-2.6.0 (groovy-ssh-2.6.0, jsch-0.1.53, groovy-2.4.4, java-1.8.0_92)
### Steps to reproduce
1. Connect to a remote that has a directory
2. Attempt to get that directory to a local directory that does not yet exist

``` groovy
task getDirectory << {
    println ssh.version
    ssh.run {
        session(remotes.machine) {
            get from: "/Share/directory", into: "$buildDir/subdirectory"
        }
    }
}
```

Workaround is to use 2.3.0 or to manually create the directory before getting.  

The error is an SFTP error, which I'm not sure is correct

```
C:\temp\ssh-folder-bug>gradlew getDir -s
:getDirectory
gradle-ssh-plugin-2.6.0 (groovy-ssh-2.6.0, jsch-0.1.53, groovy-2.4.4, java-1.8.0_92)
Host key checking is off. It may be vulnerable to man-in-the-middle attacks.
Failed SFTP GET: machine:/Share/directory -> C:\temp\ssh-folder-bug\build\subdirectory
:getDirectory FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\temp\ssh-folder-bug\build.gradle' line: 21

* What went wrong:
Execution failed for task ':getDirectory'.
> Failed SFTP GET: machine:/Share/directory -> C:\temp\ssh-folder-bug\build\subdirectory: (SSH_FX_FAILURE: An error occurred): not supported to get directory /Share/directory

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':getDirectory'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.hidetake.groovy.ssh.operation.SftpFailureException: Failed SFTP GET: machine:/Share/directory -> C:\temp\ssh-folder-bug\build\subdirectory: (SSH_FX_FAILURE: An error occurred): not supported to get directory /Share/directory
        at org.hidetake.groovy.ssh.operation.SftpException.createFrom(SftpException.groovy:18)
        at org.hidetake.groovy.ssh.operation.SftpOperations.tryCatchSftpException(SftpOperations.groovy:163)
        at org.hidetake.groovy.ssh.operation.SftpOperations.getFile(SftpOperations.groovy:38)
        at org.hidetake.groovy.ssh.session.transfer.get.Sftp$_get_closure1.doCall(Sftp.groovy:27)
        at org.hidetake.groovy.ssh.session.transfer.get.Sftp$_get_closure1.doCall(Sftp.groovy)
        at org.hidetake.groovy.ssh.util.Utility.callWithDelegate(Utility.groovy:17)
        at org.hidetake.groovy.ssh.operation.DefaultOperations.sftp(DefaultOperations.groovy:69)
        at org.hidetake.groovy.ssh.operation.Operations$sftp.call(Unknown Source)
        at org.hidetake.groovy.ssh.session.transfer.get.Sftp.get(Sftp.groovy:26)
        at org.hidetake.groovy.ssh.session.transfer.get.Provider$get.call(Unknown Source)
        at org.hidetake.groovy.ssh.session.transfer.FileGet$Trait$Helper.getInternal(FileGet.groovy:95)
        at org.hidetake.groovy.ssh.session.transfer.FileGet$Trait$Helper.getInternal(FileGet.groovy:72)
        at org.hidetake.groovy.ssh.session.transfer.FileGet$Trait$Helper.get(FileGet.groovy:40)
        at org.hidetake.groovy.ssh.session.transfer.FileGet$Trait$Helper$get.call(Unknown Source)
        at org.hidetake.groovy.ssh.session.SessionHandler.get(SessionHandler.groovy)
        at build_b1z2u8j3euo5f57dvq374h9l5$_run_closure2$_closure5$_closure6.doCall(C:\temp\ssh-folder-bug\build.gradle:21)
        at build_b1z2u8j3euo5f57dvq374h9l5$_run_closure2$_closure5$_closure6.doCall(C:\temp\ssh-folder-bug\build.gradle)
        at org.hidetake.groovy.ssh.util.Utility.callWithDelegate(Utility.groovy:17)
        at org.hidetake.groovy.ssh.session.Executor$_wetRun_closure2.doCall(Executor.groovy:71)
        at org.hidetake.groovy.ssh.session.Executor.wetRun(Executor.groovy:66)
        at org.hidetake.groovy.ssh.session.Executor.execute(Executor.groovy:50)
        at org.hidetake.groovy.ssh.session.Executor$execute.call(Unknown Source)
        at org.hidetake.groovy.ssh.core.Service.run(Service.groovy:78)
        at org.hidetake.groovy.ssh.core.Service$run.call(Unknown Source)
        at build_b1z2u8j3euo5f57dvq374h9l5$_run_closure2.doCall(C:\temp\ssh-folder-bug\build.gradle:19)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: 4: not supported to get directory /Share/directory
        at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:915)
        at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:877)
        at com.jcraft.jsch.ChannelSftp$get.call(Unknown Source)
        at org.hidetake.groovy.ssh.operation.SftpOperations$_getFile_closure1.doCall(SftpOperations.groovy:39)
        at org.hidetake.groovy.ssh.operation.SftpOperations$_getFile_closure1.doCall(SftpOperations.groovy)
        at org.hidetake.groovy.ssh.operation.SftpOperations.tryCatchSftpException(SftpOperations.groovy:158)
        ... 89 more


BUILD FAILED

Total time: 3.69 secs
```

**Comment by skazzyy** [comment]
Looks like this pull request introduced the issue... Should I move this issue to groovy-ssh?

https://github.com/int128/groovy-ssh/pull/163

**Comment by skazzyy** [comment]
So there's another bug when getting a directory, that if the directory contains nested sub-directories, 4 levels deep, the transfer fails.  So the only workaround I know of is locking in to version 2.3.0.

**Comment by int128** [comment]
> So there's another bug when getting a directory, that if the directory contains nested sub-directories, 4 levels deep, the transfer fails.

This critical bug has been fixed in 2.7.2. Thanks a lot.

> no longer get a file or directory into a local directory that doesn't exist.

Currently it is an expected behavior but may be improved in the future.
https://gradle-ssh-plugin.github.io/docs/#_transfer_a_file_or_directory
